=== NachiMK/nodejs/ods/poc/persons-complex-single.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "persons-complex-single",
  "type": "object",
  "properties": {
    "Id": {
      "type": "number"
    },
    "FirstName": {
      "type": "string"
    },
    "LastName": {
      "type": "string"
    },
    "Gender": {
      "type": "string"
    },
    "DateOfBirth": {
      "type": "string",
      "format": "date"
    },
    "IsActive": {
      "type": "boolean"
    },
    "Salary": {
      "type": [
        "number",
        "null"
      ]
    },
    "PhoneNumber": {
      "type": [
        "number",
        "string"
      ]
    },
    "Spouse": {
      "type": "object",
      "properties": {
        "Id": {
          "type": "number"
        },
        "SpouseName": {
          "type": "string"
        },
        "SpouseDOB": {
          "type": "string",
          "format": "date"
        }
      }
    },
    "Children": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "Benefits": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "Id": {
            "type": "number"
          },
          "BenefitType": {
            "type": "string"
          },
          "BenefitName": {
            "type": "string"
          },
          "EffectiveDate": {
            "type": "string",
            "format": "date"
          },
          "CoveredBenefits": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "Provider": {
            "type": "object",
            "properties": {
              "Id": {
                "type": "number"
              },
              "Name": {
                "type": "string"
              },
              "ERLocations": {
                "type": "array",
                "items": {
                  "type": "string"
                }
              }
            }
          },
          "IsActive": {
            "type": "string"
          }
        },
        "required": [
          "Id",
          "BenefitType",
          "BenefitName",
          "EffectiveDate",
          "CoveredBenefits",
          "Provider",
          "IsActive"
        ]
      }
    }
  }
}

=== NachiMK/nodejs/ods/poc/persons-etl-default.json
{
  "Id": -999999.99,
  "FirstName": "",
  "LastName": "",
  "Gender": "",
  "DateOfBirth": "",
  "IsActive": false,
  "Salary": -999999.99,
  "PhoneNumber": "",
  "Spouse": {
    "Id": -999999.99,
    "SpouseName": "",
    "SpouseDOB": ""
  },
  "Children": [],
  "Benefits": [
    {
      "Id": -999999.99,
      "BenefitType": "",
      "BenefitName": "",
      "EffectiveDate": "",
      "CoveredBenefits": [],
      "Provider": {
        "Id": -999999.99,
        "Name": "",
        "ERLocations": []
      },
      "IsActive": ""
    }
  ]
}
